// Code generated by sails-client-gen. DO NOT EDIT.
#[allow(unused_imports)]
use sails_rs::{client::*, collections::*, prelude::*};
pub struct AgentStorageClientProgram;
impl sails_rs::client::Program for AgentStorageClientProgram {}
pub trait AgentStorageClient {
    type Env: sails_rs::client::GearEnv;
    fn agent_storage(
        &self,
    ) -> sails_rs::client::Service<agent_storage::AgentStorageImpl, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> AgentStorageClient
    for sails_rs::client::Actor<AgentStorageClientProgram, E>
{
    type Env = E;
    fn agent_storage(
        &self,
    ) -> sails_rs::client::Service<agent_storage::AgentStorageImpl, Self::Env> {
        self.service(stringify!(AgentStorage))
    }
}
pub trait AgentStorageClientCtors {
    type Env: sails_rs::client::GearEnv;
    fn create(
        self,
    ) -> sails_rs::client::PendingCtor<AgentStorageClientProgram, io::Create, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> AgentStorageClientCtors
    for sails_rs::client::Deployment<AgentStorageClientProgram, E>
{
    type Env = E;
    fn create(
        self,
    ) -> sails_rs::client::PendingCtor<AgentStorageClientProgram, io::Create, Self::Env> {
        self.pending_ctor(())
    }
}

pub mod io {
    use super::*;
    sails_rs::io_struct_impl!(Create () -> ());
}

pub mod agent_storage {
    use super::*;
    pub trait AgentStorage {
        type Env: sails_rs::client::GearEnv;
        fn put(
            &mut self,
            key: String,
            value: Vec<u8>,
            ttl_blocks: u32,
        ) -> sails_rs::client::PendingCall<io::Put, Self::Env>;
        fn remove(&mut self, key: String) -> sails_rs::client::PendingCall<io::Remove, Self::Env>;
        fn get(&self, key: String) -> sails_rs::client::PendingCall<io::Get, Self::Env>;
        fn keys(&self) -> sails_rs::client::PendingCall<io::Keys, Self::Env>;
    }
    pub struct AgentStorageImpl;
    impl<E: sails_rs::client::GearEnv> AgentStorage for sails_rs::client::Service<AgentStorageImpl, E> {
        type Env = E;
        fn put(
            &mut self,
            key: String,
            value: Vec<u8>,
            ttl_blocks: u32,
        ) -> sails_rs::client::PendingCall<io::Put, Self::Env> {
            self.pending_call((key, value, ttl_blocks))
        }
        fn remove(&mut self, key: String) -> sails_rs::client::PendingCall<io::Remove, Self::Env> {
            self.pending_call((key,))
        }
        fn get(&self, key: String) -> sails_rs::client::PendingCall<io::Get, Self::Env> {
            self.pending_call((key,))
        }
        fn keys(&self) -> sails_rs::client::PendingCall<io::Keys, Self::Env> {
            self.pending_call(())
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(Put (key: String, value: Vec<u8>, ttl_blocks: u32) -> Result<(), String>);
        sails_rs::io_struct_impl!(Remove (key: String) -> Option<Vec<u8>>);
        sails_rs::io_struct_impl!(Get (key: String) -> Option<Vec<u8>>);
        sails_rs::io_struct_impl!(Keys () -> Vec<String>);
    }
}
